<?php

namespace Salma\SymCartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository {

    public function getCurrentOfferForProduct($product) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.product = :product')
                ->andWhere('c.status= :status')
                ->andWhere("c.startDate <= :timenow")
                ->andWhere("c.endDate >= :timenow ")
                ->setParameter('status', "visible")
                ->setParameter('product', $product)
                ->setParameter('timenow', new \DateTime("now"));



        return $qb->getQuery()
                        ->getResult();
    }

    public function getCurrentOffers() {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.status= :status')
                ->andWhere("c.startDate <= :timenow")
                ->andWhere("c.endDate >= :timenow ")
                ->setParameter('status', "visible")
                ->setParameter('timenow', new \DateTime("now"));



        return $qb->getQuery()
                        ->getResult();
    }
    
   

}
