<?php

namespace Salma\SymCartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * orderProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orderProductsRepository extends EntityRepository {

    public function getProductsForOrder($order_id) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.order_id = :order_id')
                ->setParameter('order_id', $order_id);



        return $qb->getQuery()
                        ->getResult();
    }

}
