<?php

namespace Salma\SymCartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
     public function getProductsForSection($section_id)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.section_id = :section_id')
                   ->andWhere('c.status= :status') 
                ->setParameter('status', "visible")
                   ->setParameter('section_id', $section_id);

       

        return $qb->getQuery()
                  ->getResult();
    }
}
